version: '3.7'

services:
    minio:
        restart: always
        image: minio/minio
        container_name: mlflow_s3
        ports:
        #    - "9000:9000"
            - "5001:9001"
        command: server /data --console-address ':9001' --address ':9000'
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
        volumes:
            - minio_data:/data

    mc:
        image: minio/mc
        depends_on:
            - minio
        container_name: mc
        environment:
            - MINIO_HOST_PORT=${MINIO_HOST_PORT:-minio:9000}
            - MLFLOW_USER_SECRET=${MLFLOW_USER_SECRET}        
        entrypoint:
        - /bin/sh
        - -c
        - |
            /tmp/wait-for-it.sh "${MINIO_HOST_PORT}" &&
            mc alias set minio "http://${MINIO_HOST_PORT}" "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}" &&          
            # Create the policy (idempotent) — file path must be non-empty!
            mc admin policy create minio mlflow-policy /tmp/mlflow-policy.json || true &&

            # Create the mlflow user if it doesn't exist
            mc admin user add minio mlflow-user "${MLFLOW_USER_SECRET}" || true &&

            # Attach the policy to user
            mc admin policy attach minio mlflow-policy --user mlflow-user || true &&

            # Make sure the bucket exists
            mc mb minio/mlflow || true &&
            exit 0
        volumes:
            - /home/limcheekin/docker/volumes/mlflow/wait-for-it.sh:/tmp/wait-for-it.sh
            - /home/limcheekin/docker/volumes/mlflow/mlflow-policy.json:/tmp/mlflow-policy.json
    web:
        restart: always
        build: ./mlflow
        container_name: mlflow_server
        depends_on:
            - mc
        ports:
            - "5000:5000"
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://${MINIO_HOST_PORT}
            - MLFLOW_S3_IGNORE_TLS=true # If you're using HTTP or a self-signed certificate with MinIO
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=us-east-1
            - DATABASE_URL=${DATABASE_URL:-postgresql://mlflow:password@host:5432/mlflow}
        command: mlflow server --backend-store-uri ${DATABASE_URL} --default-artifact-root s3://mlflow/ --serve-artifacts --host 0.0.0.0

volumes:
    minio_data:
