version: '3.7'

services:
    minio:
        restart: always
        image: minio/minio
        container_name: mlflow_s3
        #ports:
        #    - "9000:9000"
        #    - "9001:9001"
        command: server /data --console-address ':9001' --address ':9000'
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
        volumes:
            - minio_data:/data

    mc:
        image: minio/mc
        depends_on:
            - minio
        container_name: mc
        environment:
            - MINIO_HOST_PORT=${MINIO_HOST_PORT:-minio:9000}        
        entrypoint: >
            /bin/sh -c "
            /tmp/wait-for-it.sh ${MINIO_HOST_PORT} &&
            /usr/bin/mc alias set minio http://${MINIO_HOST_PORT} ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
            /usr/bin/mc mb minio/mlflow;
            exit 0;
            "
        volumes:
            - ./wait-for-it.sh:/tmp/wait-for-it.sh

    db:
        restart: always
        image: mysql/mysql-server
        container_name: mlflow_db
        #ports:
        #    - "3306:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql

    web:
        restart: always
        build: ./mlflow
        container_name: mlflow_server
        depends_on:
            - mc
            - db
        ports:
            - "5000:5000"
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://${MINIO_HOST_PORT}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - MYSQL_DATABASE_URL=${MYSQL_DATABASE_URL:-mysql+pymysql://user:password@host:3306/db}
        command: mlflow server --backend-store-uri ${MYSQL_DATABASE_URL} --default-artifact-root s3://mlflow/ --host 0.0.0.0

volumes:
    dbdata:
    minio_data:
